/* ------------------------------------------------------------ */
/*  Generated by Enterprise Architect Version 15.2              */
/*  Created On : 02-Feb-2021 15:20:02                           */
/*  DBMS       : SQL Server                                     */
/*  Notes      : Script to create EA schema                     */
/* ------------------------------------------------------------ */
/* Drop Tables */

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_attribute]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_attribute]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_attributeconstraints]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_attributeconstraints]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_attributetag]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_attributetag]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_authors]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_authors]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_cardinality]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_cardinality]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_category]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_category]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_clients]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_clients]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_complexitytypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_complexitytypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_connector]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_connector]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_connectorconstraint]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_connectorconstraint]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_connectortag]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_connectortag]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_connectortypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_connectortypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_constants]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_constants]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_constrainttypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_constrainttypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_datatypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_datatypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_diagram]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_diagram]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_diagramlinks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_diagramlinks]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_diagramobjects]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_diagramobjects]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_diagramtypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_diagramtypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_document]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_document]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_ecf]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_ecf]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_efforttypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_efforttypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_files]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_files]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_genopt]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_genopt]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_glossary]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_glossary]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_html]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_html]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_image]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_image]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_implement]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_implement]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_issues]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_issues]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_lists]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_lists]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_mainttypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_mainttypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_method]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_method]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_metrictypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_metrictypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_object]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_object]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectconstraint]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectconstraint]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objecteffort]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objecteffort]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectfiles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectfiles]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectmetrics]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectmetrics]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectproblems]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectproblems]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectproperties]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectproperties]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectrequires]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectrequires]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectresource]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectresource]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectrisks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectrisks]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objectscenarios]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objectscenarios]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objecttests]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objecttests]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objecttrx]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objecttrx]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_objecttypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_objecttypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_ocf]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_ocf]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_operation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_operation]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_operationparams]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_operationparams]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_operationposts]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_operationposts]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_operationpres]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_operationpres]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_operationtag]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_operationtag]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_package]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_package]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_palette]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_palette]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_paletteitem]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_paletteitem]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_phase]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_phase]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_primitives]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_primitives]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_problemtypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_problemtypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_projectroles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_projectroles]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_propertytypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_propertytypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_requiretypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_requiretypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_resources]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_resources]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_risktypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_risktypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_roleconstraint]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_roleconstraint]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_rtf]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_rtf]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_rtfreport]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_rtfreport]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_rules]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_rules]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_scenariotypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_scenariotypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_script]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_script]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secgroup]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secgroup]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secgrouppermission]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secgrouppermission]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_seclocks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_seclocks]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secpermission]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secpermission]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secpolicies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secpolicies]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secuser]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secuser]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secusergroup]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secusergroup]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_secuserpermission]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_secuserpermission]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_snapshot]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_snapshot]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_statustypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_statustypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_stereotypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_stereotypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_taggedvalue]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_taggedvalue]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_tasks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_tasks]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_tcf]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_tcf]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_template]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_template]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_testclass]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_testclass]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_testplans]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_testplans]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_testtypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_testtypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_trxtypes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_trxtypes]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_umlpattern]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_umlpattern]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_version]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_version]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_xref]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_xref]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_xrefsystem]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_xrefsystem]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[t_xrefuser]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [t_xrefuser]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[usys_system]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usys_system]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[usysOldTables]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usysOldTables]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[usysQueries]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usysQueries]
GO

IF EXISTS (SELECT 1 FROM sysobjects WHERE id = object_id(N'[usysTables]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usysTables]
GO

/* Create Tables */

CREATE TABLE [t_attribute]
(
	[Object_ID] int DEFAULT ((0)),
	[Name] nvarchar(255),
	[Scope] nvarchar(50),
	[Stereotype] nvarchar(50),
	[Containment] nvarchar(50),
	[IsStatic] int DEFAULT ((0)),
	[IsCollection] int DEFAULT ((0)),
	[IsOrdered] int DEFAULT ((0)),
	[AllowDuplicates] int DEFAULT ((0)),
	[LowerBound] nvarchar(50),
	[UpperBound] nvarchar(50),
	[Container] nvarchar(50),
	[Notes] nvarchar(max),
	[Derived] nvarchar(1),
	[ID] int NOT NULL IDENTITY (1, 1),
	[Pos] int,
	[GenOption] nvarchar(max),
	[Length] int,
	[Precision] int,
	[Scale] int,
	[Const] int,
	[Style] nvarchar(255),
	[Classifier] nvarchar(50),
	[Default] nvarchar(max),
	[Type] nvarchar(255),
	[ea_guid] nvarchar(50),
	[StyleEx] nvarchar(max),
	CONSTRAINT [pk_attribute] PRIMARY KEY CLUSTERED ([ID] ASC),
	CONSTRAINT [uq_attribute_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_attribute_classifier] 
 ON [t_attribute] ([Classifier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attribute_name] 
 ON [t_attribute] ([Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attribute_objectid] 
 ON [t_attribute] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attribute_type] 
 ON [t_attribute] ([Type] ASC)
GO


CREATE TABLE [t_attributeconstraints]
(
	[Object_ID] int DEFAULT ((0)),
	[Constraint] nvarchar(255) NOT NULL,
	[AttName] nvarchar(255),
	[Type] nvarchar(255),
	[Notes] nvarchar(max),
	[ID] int NOT NULL,
	CONSTRAINT [pk_attributeconstraints] PRIMARY KEY CLUSTERED ([ID] ASC,[Constraint] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_attributeconstraints_objid] 
 ON [t_attributeconstraints] ([Object_ID] ASC)
GO


CREATE TABLE [t_attributetag]
(
	[PropertyID] int NOT NULL IDENTITY (1, 1),
	[ElementID] int,
	[Property] nvarchar(255),
	[VALUE] nvarchar(255),
	[NOTES] nvarchar(max),
	[ea_guid] nvarchar(40),
	CONSTRAINT [pk_attributetag] PRIMARY KEY CLUSTERED ([PropertyID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_attributetag_elementid] 
 ON [t_attributetag] ([ElementID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attributetag_value] 
 ON [t_attributetag] ([VALUE] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attributetag_eaguid] 
 ON [t_attributetag] ([ea_guid] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attributetag_elementidprop] 
 ON [t_attributetag] ([ElementID] ASC,[Property] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_attributetag_property] 
 ON [t_attributetag] ([Property] ASC)
GO


CREATE TABLE [t_authors]
(
	[AuthorName] nvarchar(255) NOT NULL,
	[Roles] nvarchar(255),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_authors] PRIMARY KEY CLUSTERED ([AuthorName] ASC)
)
GO

CREATE TABLE [t_cardinality]
(
	[Cardinality] nvarchar(50) NOT NULL,
	CONSTRAINT [pk_cardinality] PRIMARY KEY CLUSTERED ([Cardinality] ASC)
)
GO

CREATE TABLE [t_category]
(
	[CategoryID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	[NOTES] nvarchar(max),
	CONSTRAINT [pk_category] PRIMARY KEY CLUSTERED ([CategoryID] ASC)
)
GO

CREATE TABLE [t_clients]
(
	[Name] nvarchar(255) NOT NULL,
	[Organisation] nvarchar(255),
	[Phone1] nvarchar(50),
	[Phone2] nvarchar(50),
	[Mobile] nvarchar(50),
	[Fax] nvarchar(50),
	[Email] nvarchar(50),
	[Roles] nvarchar(255),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_clients] PRIMARY KEY CLUSTERED ([Name] ASC)
)
GO

CREATE TABLE [t_complexitytypes]
(
	[Complexity] nvarchar(50) NOT NULL,
	[NumericWeight] int DEFAULT ((0)),
	CONSTRAINT [pk_complexitytypes] PRIMARY KEY CLUSTERED ([Complexity] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_complexitytypes_numweight] 
 ON [t_complexitytypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_connector]
(
	[Connector_ID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[Direction] nvarchar(50),
	[Notes] nvarchar(max),
	[Connector_Type] nvarchar(50),
	[SubType] nvarchar(50),
	[SourceCard] nvarchar(50),
	[SourceAccess] nvarchar(50),
	[SourceElement] nvarchar(50),
	[DestCard] nvarchar(50),
	[DestAccess] nvarchar(50),
	[DestElement] nvarchar(50),
	[SourceRole] nvarchar(255),
	[SourceRoleType] nvarchar(50),
	[SourceRoleNote] nvarchar(max),
	[SourceContainment] nvarchar(50),
	[SourceIsAggregate] int DEFAULT ((0)),
	[SourceIsOrdered] int DEFAULT ((0)),
	[SourceQualifier] nvarchar(50),
	[DestRole] nvarchar(255),
	[DestRoleType] nvarchar(50),
	[DestRoleNote] nvarchar(max),
	[DestContainment] nvarchar(50),
	[DestIsAggregate] int DEFAULT ((0)),
	[DestIsOrdered] int DEFAULT ((0)),
	[DestQualifier] nvarchar(50),
	[Start_Object_ID] int DEFAULT ((0)),
	[End_Object_ID] int DEFAULT ((0)),
	[Top_Start_Label] nvarchar(50),
	[Top_Mid_Label] nvarchar(50),
	[Top_End_Label] nvarchar(50),
	[Btm_Start_Label] nvarchar(50),
	[Btm_Mid_Label] nvarchar(50),
	[Btm_End_Label] nvarchar(50),
	[Start_Edge] int DEFAULT ((0)),
	[End_Edge] int DEFAULT ((0)),
	[PtStartX] int DEFAULT ((0)),
	[PtStartY] int DEFAULT ((0)),
	[PtEndX] int DEFAULT ((0)),
	[PtEndY] int DEFAULT ((0)),
	[SeqNo] int DEFAULT ((0)),
	[HeadStyle] int DEFAULT ((0)),
	[LineStyle] int DEFAULT ((0)),
	[RouteStyle] int DEFAULT ((0)),
	[IsBold] int DEFAULT ((0)),
	[LineColor] int DEFAULT ((0)),
	[Stereotype] nvarchar(50),
	[VirtualInheritance] nvarchar(1),
	[LinkAccess] nvarchar(50),
	[PDATA1] nvarchar(255),
	[PDATA2] nvarchar(max),
	[PDATA3] nvarchar(255),
	[PDATA4] nvarchar(255),
	[PDATA5] nvarchar(max),
	[DiagramID] int DEFAULT ((0)),
	[ea_guid] nvarchar(40),
	[SourceConstraint] nvarchar(255),
	[DestConstraint] nvarchar(255),
	[SourceIsNavigable] int NOT NULL DEFAULT ((0)),
	[DestIsNavigable] int NOT NULL DEFAULT ((0)),
	[IsRoot] int NOT NULL DEFAULT ((0)),
	[IsLeaf] int NOT NULL DEFAULT ((0)),
	[IsSpec] int NOT NULL DEFAULT ((0)),
	[SourceChangeable] nvarchar(12),
	[DestChangeable] nvarchar(12),
	[SourceTS] nvarchar(12),
	[DestTS] nvarchar(12),
	[StateFlags] nvarchar(255),
	[ActionFlags] nvarchar(255),
	[IsSignal] int NOT NULL DEFAULT ((0)),
	[IsStimulus] int NOT NULL DEFAULT ((0)),
	[DispatchAction] nvarchar(255),
	[Target2] int,
	[StyleEx] nvarchar(max),
	[SourceStereotype] nvarchar(255),
	[DestStereotype] nvarchar(255),
	[SourceStyle] nvarchar(max),
	[DestStyle] nvarchar(max),
	[EventFlags] nvarchar(255),
	CONSTRAINT [pk_connector] PRIMARY KEY CLUSTERED ([Connector_ID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_connector_connectortype] 
 ON [t_connector] ([Connector_Type] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_diagramid] 
 ON [t_connector] ([DiagramID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_endobjectid] 
 ON [t_connector] ([End_Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_endobjidconnid] 
 ON [t_connector] ([End_Object_ID] ASC,[Connector_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_seqno] 
 ON [t_connector] ([SeqNo] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_startobjectid] 
 ON [t_connector] ([Start_Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_startobjidconnid] 
 ON [t_connector] ([Start_Object_ID] ASC,[Connector_ID] ASC)
GO
CREATE UNIQUE NONCLUSTERED INDEX [uq_connector_eaguid] 
 ON [t_connector] ([ea_guid] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_pdata1] 
 ON [t_connector] ([PDATA1] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connector_pdata3] 
 ON [t_connector] ([PDATA3] ASC)
GO


CREATE TABLE [t_connectorconstraint]
(
	[ConnectorID] int NOT NULL DEFAULT ((0)),
	[Constraint] nvarchar(255) NOT NULL,
	[ConstraintType] nvarchar(50),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_connectorconstraint] PRIMARY KEY CLUSTERED ([ConnectorID] ASC,[Constraint] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_connectorconstraint_connid] 
 ON [t_connectorconstraint] ([ConnectorID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connectorconstraint_constr] 
 ON [t_connectorconstraint] ([Constraint] ASC)
GO


CREATE TABLE [t_connectortag]
(
	[PropertyID] int NOT NULL IDENTITY (1, 1),
	[ElementID] int,
	[Property] nvarchar(255),
	[VALUE] nvarchar(255),
	[NOTES] nvarchar(max),
	[ea_guid] nvarchar(40),
	CONSTRAINT [pk_connectortag] PRIMARY KEY CLUSTERED ([PropertyID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_connectortag_elementid] 
 ON [t_connectortag] ([ElementID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connectortag_property] 
 ON [t_connectortag] ([Property] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connectortag_value] 
 ON [t_connectortag] ([VALUE] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_connectortag_eaguid] 
 ON [t_connectortag] ([ea_guid] ASC)
GO


CREATE TABLE [t_connectortypes]
(
	[Connector_Type] nvarchar(50) NOT NULL,
	[Description] nvarchar(50),
	CONSTRAINT [pk_connectortypes] PRIMARY KEY CLUSTERED ([Connector_Type] ASC)
)
GO

CREATE TABLE [t_constants]
(
	[ConstantName] nvarchar(50) NOT NULL,
	[ConstantValue] nvarchar(255),
	CONSTRAINT [pk_constants] PRIMARY KEY CLUSTERED ([ConstantName] ASC)
)
GO

CREATE TABLE [t_constrainttypes]
(
	[Constraint] nvarchar(16) NOT NULL,
	[Description] nvarchar(50),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_constrainttypes] PRIMARY KEY CLUSTERED ([Constraint] ASC)
)
GO

CREATE TABLE [t_datatypes]
(
	[Type] nvarchar(50),
	[ProductName] nvarchar(50),
	[DataType] nvarchar(50),
	[Size] int,
	[MaxLen] int,
	[MaxPrec] int,
	[MaxScale] int DEFAULT ((0)),
	[DefaultLen] int,
	[DefaultPrec] int,
	[DefaultScale] int,
	[User] int,
	[PDATA1] nvarchar(255),
	[PDATA2] nvarchar(255),
	[PDATA3] nvarchar(255),
	[PDATA4] nvarchar(255),
	[HasLength] nvarchar(50),
	[GenericType] nvarchar(255),
	[DatatypeID] int NOT NULL IDENTITY (1, 1),
	CONSTRAINT [pk_datatypes] PRIMARY KEY CLUSTERED ([DatatypeID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_datatype_datatype] 
 ON [t_datatypes] ([DataType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_datatype_productname] 
 ON [t_datatypes] ([ProductName] ASC)
GO


CREATE TABLE [t_diagram]
(
	[Diagram_ID] int NOT NULL IDENTITY (1, 1),
	[Package_ID] int DEFAULT ((1)),
	[ParentID] int DEFAULT ((0)),
	[Diagram_Type] nvarchar(50),
	[Name] nvarchar(255),
	[Version] nvarchar(50) DEFAULT ('1.0'),
	[Author] nvarchar(255),
	[ShowDetails] int DEFAULT ((0)),
	[Notes] nvarchar(max),
	[Stereotype] nvarchar(50),
	[AttPub] int NOT NULL DEFAULT ((1)),
	[AttPri] int NOT NULL DEFAULT ((1)),
	[AttPro] int NOT NULL DEFAULT ((1)),
	[Orientation] nvarchar(1) DEFAULT ('P'),
	[cx] int DEFAULT ((0)),
	[cy] int DEFAULT ((0)),
	[Scale] int DEFAULT ((100)),
	[CreatedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[ModifiedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[HTMLPath] nvarchar(255),
	[ShowForeign] int NOT NULL DEFAULT ((1)),
	[ShowBorder] int NOT NULL DEFAULT ((1)),
	[ShowPackageContents] int NOT NULL DEFAULT ((1)),
	[PDATA] nvarchar(255),
	[Locked] int NOT NULL DEFAULT ((0)),
	[ea_guid] nvarchar(40),
	[TPos] int,
	[Swimlanes] nvarchar(255),
	[StyleEx] nvarchar(max),
	CONSTRAINT [pk_diagram] PRIMARY KEY CLUSTERED ([Diagram_ID] ASC),
	CONSTRAINT [uq_diagram_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_diagram_diagramtype] 
 ON [t_diagram] ([Diagram_Type] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_diagram_packageid] 
 ON [t_diagram] ([Package_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_diagram_parentid] 
 ON [t_diagram] ([ParentID] ASC)
GO


CREATE TABLE [t_diagramlinks]
(
	[DiagramID] int,
	[ConnectorID] int,
	[Geometry] nvarchar(max),
	[Style] nvarchar(255),
	[Hidden] int NOT NULL DEFAULT ((0)),
	[Path] nvarchar(255),
	[Instance_ID] int NOT NULL IDENTITY (1, 1),
	CONSTRAINT [pk_diagramlinks] PRIMARY KEY CLUSTERED ([Instance_ID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_diagramlinks_connectorid] 
 ON [t_diagramlinks] ([ConnectorID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_diagramlinks_diagramid] 
 ON [t_diagramlinks] ([DiagramID] ASC)
GO


CREATE TABLE [t_diagramobjects]
(
	[Diagram_ID] int DEFAULT ((0)),
	[Object_ID] int DEFAULT ((0)),
	[RectTop] int DEFAULT ((0)),
	[RectLeft] int DEFAULT ((0)),
	[RectRight] int DEFAULT ((0)),
	[RectBottom] int DEFAULT ((0)),
	[Sequence] int DEFAULT ((0)),
	[ObjectStyle] nvarchar(255),
	[Instance_ID] int NOT NULL IDENTITY (1, 1),
	CONSTRAINT [pk_diagramobjects] PRIMARY KEY CLUSTERED ([Instance_ID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_diagramobjects_diagramid] 
 ON [t_diagramobjects] ([Diagram_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_diagramobjects_objectid] 
 ON [t_diagramobjects] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_diagramobjects_sequence] 
 ON [t_diagramobjects] ([Sequence] ASC)
GO


CREATE TABLE [t_diagramtypes]
(
	[Diagram_Type] nvarchar(50) NOT NULL,
	[Name] nvarchar(255),
	[Package_ID] int DEFAULT ((0)),
	CONSTRAINT [pk_diagramtypes] PRIMARY KEY CLUSTERED ([Diagram_Type] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_diagramtypes_packageid] 
 ON [t_diagramtypes] ([Package_ID] ASC)
GO


CREATE TABLE [t_document]
(
	[DocID] nvarchar(40) NOT NULL,
	[DocName] nvarchar(100),
	[Notes] nvarchar(255),
	[Style] nvarchar(255),
	[ElementID] nvarchar(40) NOT NULL,
	[ElementType] nvarchar(50) NOT NULL,
	[StrContent] nvarchar(max),
	[BinContent] image,
	[DocType] nvarchar(100),
	[Author] nvarchar(255),
	[Version] nvarchar(50),
	[IsActive] int DEFAULT ((1)),
	[Sequence] int DEFAULT ((0)),
	[DocDate] datetime,
	CONSTRAINT [pk_document] PRIMARY KEY CLUSTERED ([DocID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_document_elementid] 
 ON [t_document] ([ElementID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_document_author] 
 ON [t_document] ([Author] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_document_doctype] 
 ON [t_document] ([DocType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_document_style] 
 ON [t_document] ([Style] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_document_version] 
 ON [t_document] ([Version] ASC)
GO


CREATE TABLE [t_ecf]
(
	[ECFID] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[Weight] float DEFAULT ((1)),
	[Value] float DEFAULT ((0)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_ecf] PRIMARY KEY CLUSTERED ([ECFID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_ecf_weight] 
 ON [t_ecf] ([Weight] ASC)
GO


CREATE TABLE [t_efforttypes]
(
	[EffortType] nvarchar(12) NOT NULL,
	[Description] nvarchar(255),
	[NumericWeight] float DEFAULT ((0)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_efforttypes] PRIMARY KEY CLUSTERED ([EffortType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_efforttypes_numericweight] 
 ON [t_efforttypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_files]
(
	[FileID] nvarchar(50) NOT NULL,
	[AppliesTo] nvarchar(50) NOT NULL,
	[Category] nvarchar(100) NOT NULL,
	[Name] nvarchar(150) NOT NULL,
	[File] nvarchar(255),
	[Notes] nvarchar(max),
	[FileDate] datetime,
	[FileSize] int,
	CONSTRAINT [pk_files] PRIMARY KEY CLUSTERED ([FileID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_files_appliesto] 
 ON [t_files] ([AppliesTo] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_files_appliestoname] 
 ON [t_files] ([AppliesTo] ASC,[Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_files_appliestonamesize] 
 ON [dbo].[t_files] ([AppliesTo] ASC,[Name] ASC,[FileSize] ASC)
GO 
CREATE NONCLUSTERED INDEX [ix_files_appliestonamedatesize] 
 ON [dbo].[t_files] ([AppliesTo] ASC,[Name] ASC,[FileDate] ASC,[FileSize] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_files_category] 
 ON [t_files] ([Category] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_files_filesize] 
 ON [t_files] ([FileSize] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_files_name] 
 ON [t_files] ([Name] ASC)
GO


CREATE TABLE [t_genopt]
(
	[AppliesTo] nvarchar(12),
	[Option] nvarchar(max)
)
GO
CREATE CLUSTERED INDEX [ix_genopt_appliesto] 
 ON [t_genopt] ([AppliesTo] ASC)
GO


CREATE TABLE [t_glossary]
(
	[Term] nvarchar(255),
	[Type] nvarchar(255),
	[Meaning] nvarchar(max),
	[GlossaryID] int NOT NULL IDENTITY (1, 1),
	CONSTRAINT [pk_glossary] PRIMARY KEY CLUSTERED ([GlossaryID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_glossary_term] 
 ON [t_glossary] ([Term] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_glossary_type] 
 ON [t_glossary] ([Type] ASC)
GO


CREATE TABLE [t_html]
(
	[Type] nvarchar(50),
	[Template] nvarchar(max)
)
GO
CREATE CLUSTERED INDEX [ix_html_type] 
 ON [t_html] ([Type] ASC)
GO


CREATE TABLE [t_image]
(
	[ImageID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	[Image] image,
	CONSTRAINT [pk_image] PRIMARY KEY CLUSTERED ([ImageID] ASC)
)
GO

CREATE TABLE [t_implement]
(
	[Type] nvarchar(50)
)
GO
CREATE CLUSTERED INDEX [ix_implement_type] 
 ON [t_implement] ([Type] ASC)
GO


CREATE TABLE [t_issues]
(
	[Issue] nvarchar(255),
	[IssueDate] datetime,
	[Owner] nvarchar(255),
	[Status] nvarchar(50),
	[Notes] nvarchar(max),
	[Resolver] nvarchar(255),
	[DateResolved] datetime,
	[Resolution] nvarchar(max),
	[IssueID] int NOT NULL IDENTITY (1, 1),
	[Category] nvarchar(255),
	[Priority] nvarchar(50),
	[Severity] nvarchar(50),
	[IssueType] nvarchar(100),
	CONSTRAINT [pk_issues] PRIMARY KEY CLUSTERED ([IssueID] ASC)
)
GO

CREATE TABLE [t_lists]
(
	[ListID] nvarchar(50) NOT NULL,
	[Category] nvarchar(100) NOT NULL,
	[Name] nvarchar(150) NOT NULL,
	[NVal] int,
	[Notes] nvarchar(max),
	CONSTRAINT [pk_lists] PRIMARY KEY CLUSTERED ([ListID] ASC)
)
GO

CREATE TABLE [t_mainttypes]
(
	[MaintType] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_mainttypes] PRIMARY KEY CLUSTERED ([MaintType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_mainttypes_numericweight] 
 ON [t_mainttypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_method]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Name] nvarchar(255) NOT NULL,
	[Scope] nvarchar(50),
	[Type] nvarchar(50),
	CONSTRAINT [pk_method] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Name] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_method_objectid] 
 ON [t_method] ([Object_ID] ASC)
GO


CREATE TABLE [t_metrictypes]
(
	[Metric] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_metrictypes] PRIMARY KEY CLUSTERED ([Metric] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_metrictypes_numericweight] 
 ON [t_metrictypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_object]
(
	[Object_ID] int NOT NULL IDENTITY (1, 1),
	[Object_Type] nvarchar(255),
	[Diagram_ID] int DEFAULT ((0)),
	[Name] nvarchar(255),
	[Alias] nvarchar(255),
	[Author] nvarchar(255),
	[Version] nvarchar(50) DEFAULT ('1.0'),
	[Note] nvarchar(max),
	[Package_ID] int DEFAULT ((0)),
	[Stereotype] nvarchar(255),
	[NType] int DEFAULT ((0)),
	[Complexity] nvarchar(50) DEFAULT ('2'),
	[Effort] int DEFAULT ((0)),
	[Style] nvarchar(255),
	[Backcolor] int DEFAULT ((0)),
	[BorderStyle] int DEFAULT ((0)),
	[BorderWidth] int DEFAULT ((0)),
	[Fontcolor] int DEFAULT ((0)),
	[Bordercolor] int DEFAULT ((0)),
	[CreatedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[ModifiedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[Status] nvarchar(50),
	[Abstract] nvarchar(1),
	[Tagged] int DEFAULT ((0)),
	[PDATA1] nvarchar(255),
	[PDATA2] nvarchar(max),
	[PDATA3] nvarchar(max),
	[PDATA4] nvarchar(max),
	[PDATA5] nvarchar(255),
	[Concurrency] nvarchar(50),
	[Visibility] nvarchar(50),
	[Persistence] nvarchar(50),
	[Cardinality] nvarchar(50),
	[GenType] nvarchar(50),
	[GenFile] nvarchar(255),
	[Header1] nvarchar(max),
	[Header2] nvarchar(max),
	[Phase] nvarchar(50),
	[Scope] nvarchar(25),
	[GenOption] nvarchar(max),
	[GenLinks] nvarchar(max),
	[Classifier] int,
	[ea_guid] nvarchar(40),
	[ParentID] int,
	[RunState] nvarchar(max),
	[Classifier_guid] nvarchar(40),
	[TPos] int,
	[IsRoot] int NOT NULL DEFAULT ((0)),
	[IsLeaf] int NOT NULL DEFAULT ((0)),
	[IsSpec] int NOT NULL DEFAULT ((0)),
	[IsActive] int NOT NULL DEFAULT ((0)),
	[StateFlags] nvarchar(255),
	[PackageFlags] nvarchar(255),
	[Multiplicity] nvarchar(50),
	[StyleEx] nvarchar(max),
	[EventFlags] nvarchar(max),
	[ActionFlags] nvarchar(255),
	CONSTRAINT [pk_object] PRIMARY KEY CLUSTERED ([Object_ID] ASC),
	CONSTRAINT [uq_object_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_object_classifier] 
 ON [t_object] ([Classifier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_classifierguid] 
 ON [t_object] ([Classifier_guid] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_name] 
 ON [t_object] ([Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_ntype] 
 ON [t_object] ([NType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_objecttype] 
 ON [t_object] ([Object_Type] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_packageid] 
 ON [t_object] ([Package_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_parentid] 
 ON [t_object] ([ParentID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_pdata1] 
 ON [t_object] ([PDATA1] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_pkgidpdata1class] 
 ON [t_object] ([Package_ID] ASC,[PDATA1] ASC,[Classifier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_eaguidclassifier] 
 ON [t_object] ([ea_guid] ASC,[Classifier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_object_pdata5] 
 ON [t_object] ([PDATA5] ASC)
GO


CREATE TABLE [t_objectconstraint]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Constraint] nvarchar(255) NOT NULL,
	[ConstraintType] nvarchar(30) NOT NULL,
	[Weight] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	[Status] nvarchar(50),
	CONSTRAINT [pk_objectconstraint] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[ConstraintType] ASC,[Constraint] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectconstraint_constr] 
 ON [t_objectconstraint] ([Constraint] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectconstraint_objectid] 
 ON [t_objectconstraint] ([Object_ID] ASC)
GO


CREATE TABLE [t_objecteffort]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Effort] nvarchar(255) NOT NULL,
	[EffortType] nvarchar(12),
	[EValue] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_objecteffort] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Effort] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objecteffort_objectid] 
 ON [t_objecteffort] ([Object_ID] ASC)
GO


CREATE TABLE [t_objectfiles]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[FileName] nvarchar(255) NOT NULL,
	[Type] nvarchar(50),
	[Note] nvarchar(max),
	[FileSize] nvarchar(255),
	[FileDate] nvarchar(255),
	CONSTRAINT [pk_objectfiles] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[FileName] ASC)
)
GO

CREATE TABLE [t_objectmetrics]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Metric] nvarchar(255) NOT NULL,
	[MetricType] nvarchar(12),
	[EValue] float DEFAULT ((1)),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_objectmetrics] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Metric] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectmetrics_metric] 
 ON [t_objectmetrics] ([Metric] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectmetrics_metrictype] 
 ON [t_objectmetrics] ([MetricType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectmetrics_objectid] 
 ON [t_objectmetrics] ([Object_ID] ASC)
GO


CREATE TABLE [t_objectproblems]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Problem] varchar(255) NOT NULL,
	[ProblemType] varchar(255) NOT NULL,
	[DateReported] datetime,
	[Status] nvarchar(50),
	[ProblemNotes] nvarchar(max),
	[ReportedBy] nvarchar(255),
	[ResolvedBy] nvarchar(255),
	[DateResolved] datetime,
	[Version] nvarchar(50),
	[ResolverNotes] nvarchar(max),
	[Priority] nvarchar(50),
	[Severity] nvarchar(50),
	CONSTRAINT [pk_objectproblems] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[ProblemType] ASC,[Problem] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectproblems_objectid] 
 ON [t_objectproblems] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectproblems_problem] 
 ON [t_objectproblems] ([Problem] ASC)
GO


CREATE TABLE [t_objectproperties]
(
	[PropertyID] int NOT NULL IDENTITY (1, 1),
	[Object_ID] int DEFAULT ((0)),
	[Property] nvarchar(255),
	[Value] nvarchar(255),
	[Notes] nvarchar(max),
	[ea_guid] nvarchar(40),
	CONSTRAINT [pk_objectproperties] PRIMARY KEY CLUSTERED ([PropertyID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectproperties_objectid] 
 ON [t_objectproperties] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectproperties_property] 
 ON [t_objectproperties] ([Property] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectproperties_value] 
 ON [t_objectproperties] ([Value] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectproperties_objidprop] 
 ON [t_objectproperties] ([Object_ID] ASC,[Property] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectproperties_eaguid] 
 ON [t_objectproperties] ([ea_guid] ASC)
GO


CREATE TABLE [t_objectrequires]
(
	[ReqID] int NOT NULL IDENTITY (1, 1),
	[Object_ID] int DEFAULT ((0)),
	[Requirement] nvarchar(255),
	[ReqType] nvarchar(255),
	[Status] nvarchar(50),
	[Notes] nvarchar(max),
	[Stability] nvarchar(50),
	[Difficulty] nvarchar(50),
	[Priority] nvarchar(50),
	[LastUpdate] datetime DEFAULT (getdate()),
	CONSTRAINT [pk_objectrequires] PRIMARY KEY CLUSTERED ([ReqID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectrequires_objectid] 
 ON [t_objectrequires] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectrequires_requirement] 
 ON [t_objectrequires] ([Requirement] ASC)
GO


CREATE TABLE [t_objectresource]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Resource] varchar(255) NOT NULL,
	[Role] varchar(255) NOT NULL,
	[Time] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	[PercentComplete] smallint DEFAULT ((0)),
	[DateStart] datetime,
	[DateEnd] datetime,
	[History] nvarchar(max),
	[ExpectedHours] int,
	[ActualHours] int,
	CONSTRAINT [pk_objectresource] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Resource] ASC,[Role] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectresource_objectid] 
 ON [t_objectresource] ([Object_ID] ASC)
GO


CREATE TABLE [t_objectrisks]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Risk] nvarchar(255) NOT NULL,
	[RiskType] nvarchar(12),
	[EValue] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_objectrisks] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Risk] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectrisks_objectid] 
 ON [t_objectrisks] ([Object_ID] ASC)
GO


CREATE TABLE [t_objectscenarios]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Scenario] nvarchar(255) NOT NULL,
	[ScenarioType] nvarchar(12),
	[EValue] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	[XMLContent] nvarchar(max),
	[ea_guid] nvarchar(40),
	CONSTRAINT [pk_objectscenarios] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Scenario] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objectscenarios_objectid] 
 ON [t_objectscenarios] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objectscenarios_oidevalscen] 
 ON [t_objectscenarios] ([Object_ID] ASC,[EValue] ASC,[Scenario] ASC)
GO


CREATE TABLE [t_objecttests]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[Test] nvarchar(255) NOT NULL,
	[TestClass] int NOT NULL DEFAULT ((0)),
	[TestType] nvarchar(50),
	[Notes] nvarchar(max),
	[InputData] nvarchar(max),
	[AcceptanceCriteria] nvarchar(max),
	[Status] nvarchar(32),
	[DateRun] datetime DEFAULT (getdate()),
	[Results] nvarchar(max),
	[RunBy] nvarchar(255),
	[CheckBy] nvarchar(255),
	CONSTRAINT [pk_objecttests] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[Test] ASC,[TestClass] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objecttests_objectid] 
 ON [t_objecttests] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objecttests_objidtclassstat] 
 ON [t_objecttests] ([Object_ID] ASC,[TestClass] ASC,[Status] ASC)
GO


CREATE TABLE [t_objecttrx]
(
	[Object_ID] int NOT NULL DEFAULT ((0)),
	[TRX] nvarchar(255) NOT NULL,
	[TRXType] nvarchar(12) NOT NULL,
	[Weight] float DEFAULT ((0)),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_objecttrx] PRIMARY KEY CLUSTERED ([Object_ID] ASC,[TRXType] ASC,[TRX] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objecttrx_trx] 
 ON [t_objecttrx] ([TRX] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_objecttrx_objectid] 
 ON [t_objecttrx] ([Object_ID] ASC)
GO


CREATE TABLE [t_objecttypes]
(
	[Object_Type] nvarchar(50) NOT NULL,
	[Description] nvarchar(255),
	[DesignObject] int NOT NULL DEFAULT ((0)),
	[ImageID] int DEFAULT ((0)),
	CONSTRAINT [pk_objecttypes] PRIMARY KEY CLUSTERED ([Object_Type] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_objecttypes_imageid] 
 ON [t_objecttypes] ([ImageID] ASC)
GO


CREATE TABLE [t_ocf]
(
	[ObjectType] nvarchar(50),
	[ComplexityWeight] float DEFAULT ((0))
)
GO
CREATE CLUSTERED INDEX [ix_ocf_objecttype] 
 ON [t_ocf] ([ObjectType] ASC)
GO


CREATE TABLE [t_operation]
(
	[OperationID] int NOT NULL IDENTITY (1, 1),
	[Object_ID] int DEFAULT ((0)),
	[Name] nvarchar(255),
	[Scope] nvarchar(50),
	[Type] nvarchar(255),
	[ReturnArray] nvarchar(1),
	[Stereotype] nvarchar(50),
	[IsStatic] nvarchar(1),
	[Concurrency] nvarchar(50),
	[Notes] nvarchar(max),
	[Behaviour] nvarchar(max),
	[Abstract] nvarchar(1),
	[GenOption] nvarchar(max),
	[Synchronized] nvarchar(1),
	[Pos] int,
	[Const] int,
	[Style] nvarchar(255),
	[Pure] int NOT NULL DEFAULT ((0)),
	[Throws] nvarchar(255),
	[Classifier] nvarchar(50),
	[Code] nvarchar(max),
	[IsRoot] int NOT NULL DEFAULT ((0)),
	[IsLeaf] int NOT NULL DEFAULT ((0)),
	[IsQuery] int NOT NULL DEFAULT ((0)),
	[StateFlags] nvarchar(255),
	[ea_guid] nvarchar(50),
	[StyleEx] nvarchar(max),
	CONSTRAINT [pk_operation] PRIMARY KEY CLUSTERED ([OperationID] ASC),
	CONSTRAINT [uq_operation_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_operation_classifier] 
 ON [t_operation] ([Classifier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operation_name] 
 ON [t_operation] ([Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operation_objectid] 
 ON [t_operation] ([Object_ID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operation_objectidopid] 
 ON [t_operation] ([Object_ID] ASC,[OperationID] ASC)
GO


CREATE TABLE [t_operationparams]
(
	[OperationID] int NOT NULL DEFAULT ((0)),
	[Name] nvarchar(255) NOT NULL,
	[Type] nvarchar(255),
	[Default] nvarchar(255),
	[Notes] nvarchar(max),
	[Pos] int,
	[Const] int NOT NULL DEFAULT ((0)),
	[Style] nvarchar(255),
	[Kind] nvarchar(12),
	[Classifier] nvarchar(50),
	[ea_guid] nvarchar(50),
	[StyleEx] nvarchar(max),
	CONSTRAINT [pk_operationparams] PRIMARY KEY CLUSTERED ([OperationID] ASC,[Name] ASC),
	CONSTRAINT [uq_operationparams_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_operationparams_opid] 
 ON [t_operationparams] ([OperationID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationparams_opidpos] 
 ON [t_operationparams] ([OperationID] ASC,[Pos] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationparams_classifier] 
 ON [t_operationparams] ([Classifier] ASC)
GO


CREATE TABLE [t_operationposts]
(
	[OperationID] int NOT NULL DEFAULT ((0)),
	[PostCondition] nvarchar(255) NOT NULL,
	[Type] nvarchar(255),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_operationposts] PRIMARY KEY CLUSTERED ([OperationID] ASC,[PostCondition] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_operationposts_operationid] 
 ON [t_operationposts] ([OperationID] ASC)
GO


CREATE TABLE [t_operationpres]
(
	[OperationID] int NOT NULL DEFAULT ((0)),
	[PreCondition] nvarchar(255) NOT NULL,
	[Type] nvarchar(50),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_operationpres] PRIMARY KEY CLUSTERED ([OperationID] ASC,[PreCondition] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_operationpres_operationid] 
 ON [t_operationpres] ([OperationID] ASC)
GO


CREATE TABLE [t_operationtag]
(
	[PropertyID] int NOT NULL IDENTITY (1, 1),
	[ElementID] int,
	[Property] nvarchar(255),
	[VALUE] nvarchar(255),
	[NOTES] nvarchar(max),
	[ea_guid] nvarchar(40),
	CONSTRAINT [pk_operationtag] PRIMARY KEY CLUSTERED ([PropertyID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_operationtag_elementid] 
 ON [t_operationtag] ([ElementID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationtag_value] 
 ON [t_operationtag] ([VALUE] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationtag_eaguid] 
 ON [t_operationtag] ([ea_guid] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationtag_elementidprop] 
 ON [t_operationtag] ([ElementID] ASC,[Property] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_operationtag_property] 
 ON [t_operationtag] ([Property] ASC)
GO


CREATE TABLE [t_package]
(
	[Package_ID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[Parent_ID] int DEFAULT ((0)),
	[CreatedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[ModifiedDate] datetime DEFAULT (CONVERT([datetime],CONVERT([varchar],getdate(),(1)),(1))),
	[Notes] nvarchar(max),
	[ea_guid] nvarchar(40),
	[XMLPath] nvarchar(255),
	[IsControlled] int NOT NULL DEFAULT ((0)),
	[LastLoadDate] datetime,
	[LastSaveDate] datetime,
	[Version] nvarchar(50),
	[Protected] int NOT NULL DEFAULT ((0)),
	[PkgOwner] nvarchar(255),
	[UMLVersion] nvarchar(50),
	[UseDTD] int NOT NULL DEFAULT ((0)),
	[LogXML] int NOT NULL DEFAULT ((0)),
	[CodePath] nvarchar(255),
	[Namespace] nvarchar(50),
	[TPos] int,
	[PackageFlags] nvarchar(255),
	[BatchSave] int,
	[BatchLoad] int,
	CONSTRAINT [pk_package] PRIMARY KEY CLUSTERED ([Package_ID] ASC),
	CONSTRAINT [uq_package_eaguid] UNIQUE NONCLUSTERED ([ea_guid] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_package_name] 
 ON [t_package] ([Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_package_parentid] 
 ON [t_package] ([Parent_ID] ASC)
GO


CREATE TABLE [t_palette]
(
	[PaletteID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	CONSTRAINT [pk_palette] PRIMARY KEY CLUSTERED ([PaletteID] ASC)
)
GO

CREATE TABLE [t_paletteitem]
(
	[PaletteID] int,
	[ItemID] int
)
GO
CREATE CLUSTERED INDEX [ix_paletteitem_palatteid] 
 ON [t_paletteitem] ([PaletteID] ASC)
GO


CREATE TABLE [t_phase]
(
	[PhaseID] varchar(40) NOT NULL,
	[PhaseName] varchar(100) NOT NULL,
	[PhaseNotes] nvarchar(max),
	[PhaseStyle] varchar(255),
	[StartDate] datetime,
	[EndDate] datetime,
	[PhaseContent] nvarchar(max),
	CONSTRAINT [pk_phase] PRIMARY KEY CLUSTERED ([PhaseID] ASC)
)
GO

CREATE TABLE [t_primitives]
(
	[Datatype] nvarchar(50) NOT NULL,
	[Description] nvarchar(50),
	CONSTRAINT [pk_primitives] PRIMARY KEY CLUSTERED ([Datatype] ASC)
)
GO

CREATE TABLE [t_problemtypes]
(
	[ProblemType] nvarchar(12) NOT NULL,
	[Description] nvarchar(255),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_problemtypes] PRIMARY KEY CLUSTERED ([ProblemType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_problemtypes_numericweight] 
 ON [t_problemtypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_projectroles]
(
	[Role] nvarchar(255) NOT NULL,
	[Description] nvarchar(255),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_projectroles] PRIMARY KEY CLUSTERED ([Role] ASC)
)
GO

CREATE TABLE [t_propertytypes]
(
	[Property] nvarchar(50) NOT NULL,
	[Description] nvarchar(50),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_propertytypes] PRIMARY KEY CLUSTERED ([Property] ASC)
)
GO

CREATE TABLE [t_requiretypes]
(
	[Requirement] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_requiretypes] PRIMARY KEY CLUSTERED ([Requirement] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_requiretypes_numericweight] 
 ON [t_requiretypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_resources]
(
	[Name] nvarchar(255) NOT NULL,
	[Organisation] nvarchar(255),
	[Phone1] nvarchar(50),
	[Phone2] nvarchar(50),
	[Mobile] nvarchar(50),
	[Fax] nvarchar(50),
	[Email] nvarchar(255),
	[Roles] nvarchar(255),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_resources] PRIMARY KEY CLUSTERED ([Name] ASC)
)
GO

CREATE TABLE [t_risktypes]
(
	[Risk] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((0)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_risktypes] PRIMARY KEY CLUSTERED ([Risk] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_risktypes_numericweight] 
 ON [t_risktypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_roleconstraint]
(
	[ConnectorID] int NOT NULL DEFAULT ((0)),
	[Constraint] nvarchar(255) NOT NULL,
	[ConnectorEnd] nvarchar(50) NOT NULL,
	[ConstraintType] nvarchar(12) NOT NULL,
	[Notes] nvarchar(max),
	CONSTRAINT [pk_roleconstraint] PRIMARY KEY CLUSTERED ([ConnectorID] ASC,[Constraint] ASC,[ConnectorEnd] ASC,[ConstraintType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_roleconstraint_connectorid] 
 ON [t_roleconstraint] ([ConnectorID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_roleconstraint_constraint] 
 ON [t_roleconstraint] ([Constraint] ASC)
GO


CREATE TABLE [t_rtf]
(
	[Type] nvarchar(50),
	[Template] nvarchar(max)
)
GO
CREATE CLUSTERED INDEX [ix_rtf_type] 
 ON [t_rtf] ([Type] ASC)
GO


CREATE TABLE [t_rtfreport]
(
	[TemplateID] nvarchar(200) NOT NULL,
	[RootPackage] int DEFAULT ((0)),
	[Filename] nvarchar(255),
	[Details] int NOT NULL DEFAULT ((0)),
	[ProcessChildren] int NOT NULL DEFAULT ((0)),
	[ShowDiagrams] int NOT NULL DEFAULT ((0)),
	[Heading] nvarchar(255),
	[Requirements] int NOT NULL DEFAULT ((0)),
	[Associations] int NOT NULL DEFAULT ((0)),
	[Scenarios] int NOT NULL DEFAULT ((0)),
	[ChildDiagrams] int NOT NULL DEFAULT ((0)),
	[Attributes] int NOT NULL DEFAULT ((0)),
	[Methods] int NOT NULL DEFAULT ((0)),
	[ImageType] int DEFAULT ((0)),
	[Paging] int NOT NULL DEFAULT ((0)),
	[Intro] nvarchar(max),
	[Resources] int NOT NULL DEFAULT ((1)),
	[Constraints] int NOT NULL DEFAULT ((1)),
	[Tagged] int NOT NULL DEFAULT ((0)),
	[ShowTag] int NOT NULL DEFAULT ((0)),
	[ShowAlias] int NOT NULL DEFAULT ((0)),
	[PDATA1] nvarchar(255),
	[PDATA2] nvarchar(255),
	[PDATA3] nvarchar(255),
	[PDATA4] nvarchar(max),
	CONSTRAINT [pk_rtfreport] PRIMARY KEY CLUSTERED ([TemplateID] ASC)
)
GO

CREATE TABLE [t_rules]
(
	[RuleID] nvarchar(50) NOT NULL,
	[RuleName] nvarchar(255) NOT NULL,
	[RuleType] nvarchar(255) NOT NULL,
	[RuleActive] int,
	[ErrorMsg] nvarchar(255),
	[Flags] nvarchar(255),
	[RuleOCL] nvarchar(max),
	[RuleXML] nvarchar(max),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_rules] PRIMARY KEY CLUSTERED ([RuleID] ASC)
)
GO

CREATE TABLE [t_scenariotypes]
(
	[ScenarioType] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_scenariotypes] PRIMARY KEY CLUSTERED ([ScenarioType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_scenariotypes_numericweight] 
 ON [t_scenariotypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_script]
(
	[ScriptID] int NOT NULL IDENTITY (1, 1),
	[ScriptCategory] nvarchar(100),
	[ScriptName] nvarchar(150),
	[ScriptAuthor] nvarchar(255),
	[Notes] nvarchar(max),
	[Script] nvarchar(max),
	CONSTRAINT [pk_script] PRIMARY KEY CLUSTERED ([ScriptID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_script_scriptcategory] 
 ON [t_script] ([ScriptCategory] ASC)
GO


CREATE TABLE [t_secgroup]
(
	[GroupID] nvarchar(40) NOT NULL,
	[GroupName] nvarchar(32) NOT NULL,
	[Description] nvarchar(100),
	CONSTRAINT [pk_secgroup] PRIMARY KEY CLUSTERED ([GroupID] ASC)
)
GO

CREATE TABLE [t_secgrouppermission]
(
	[GroupID] nvarchar(40) NOT NULL,
	[PermissionID] int NOT NULL,
	CONSTRAINT [pk_secgrouppermission] PRIMARY KEY CLUSTERED ([GroupID] ASC,[PermissionID] ASC)
)
GO

CREATE TABLE [t_seclocks]
(
	[UserID] nvarchar(40) NOT NULL,
	[GroupID] nvarchar(40),
	[EntityType] nvarchar(32) NOT NULL,
	[EntityID] nvarchar(40) NOT NULL,
	[Timestamp] datetime NOT NULL,
	[LockType] nvarchar(255),
	CONSTRAINT [pk_seclocks] PRIMARY KEY CLUSTERED ([EntityID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_seclocks_entityiduserid] 
 ON [t_seclocks] ([EntityID] ASC,[UserID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_seclocks_entityidtype] 
 ON [t_seclocks] ([EntityID] ASC,[EntityType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_seclocks_entityidusrtype] 
 ON [t_seclocks] ([EntityID] ASC,[UserID] ASC,[EntityType] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_seclocks_groupid] 
 ON [t_seclocks] ([GroupID] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_seclocks_groupiduserid] 
 ON [t_seclocks] ([GroupID] ASC,[UserID] ASC)
GO


CREATE TABLE [t_secpermission]
(
	[PermissionID] int NOT NULL,
	[PermissionName] nvarchar(50) NOT NULL,
	CONSTRAINT [pk_secpermission] PRIMARY KEY CLUSTERED ([PermissionID] ASC)
)
GO

CREATE TABLE [t_secpolicies]
(
	[Property] nvarchar(100) NOT NULL,
	[Value] nvarchar(255) NOT NULL,
	CONSTRAINT [pk_secpolicies] PRIMARY KEY CLUSTERED ([Property] ASC)
)
GO

CREATE TABLE [t_secuser]
(
	[UserID] nvarchar(40) NOT NULL,
    [UserLogin] nvarchar(255) NOT NULL,
	[FirstName] nvarchar(50) NOT NULL,
	[Surname] nvarchar(50) NOT NULL,
	[Department] nvarchar(50),
	[Password] nvarchar(12),
	CONSTRAINT [pk_secuser] PRIMARY KEY CLUSTERED ([UserID] ASC)
)
GO

CREATE TABLE [t_secusergroup]
(
	[UserID] nvarchar(40) NOT NULL,
	[GroupID] nvarchar(40) NOT NULL,
	CONSTRAINT [pk_secusergroup] PRIMARY KEY CLUSTERED ([UserID] ASC,[GroupID] ASC)
)
GO

CREATE TABLE [t_secuserpermission]
(
	[UserID] nvarchar(40) NOT NULL,
	[PermissionID] int NOT NULL,
	CONSTRAINT [pk_secuserpermission] PRIMARY KEY CLUSTERED ([UserID] ASC,[PermissionID] ASC)
)
GO

CREATE TABLE [t_snapshot]
(
	[SnapshotID] nvarchar(40) NOT NULL,
	[SeriesID] nvarchar(40),
	[Position] int NOT NULL,
	[SnapshotName] nvarchar(100) NOT NULL,
	[Notes] nvarchar(max),
	[Style] nvarchar(255),
	[ElementID] nvarchar(40),
	[ElementType] nvarchar(50) NOT NULL,
	[StrContent] nvarchar(max),
	[BinContent1] image,
	[BinContent2] image,
	CONSTRAINT [pk_snapshot] PRIMARY KEY CLUSTERED ([SnapshotID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_snapshot_position] 
 ON [t_snapshot] ([Position] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_snapshot_seriesid] 
 ON [t_snapshot] ([SeriesID] ASC)
GO


CREATE TABLE [t_statustypes]
(
	[Status] nvarchar(50) NOT NULL,
	[Description] nvarchar(50),
	CONSTRAINT [pk_statustypes] PRIMARY KEY CLUSTERED ([Status] ASC)
)
GO

CREATE TABLE [t_stereotypes]
(
	[Stereotype] varchar(255) NOT NULL,
	[AppliesTo] varchar(255) NOT NULL,
	[Description] nvarchar(255),
	[MFEnabled] int NOT NULL DEFAULT ((0)),
	[MFPath] nvarchar(255),
	[Metafile] image,
	[Style] nvarchar(max),
	[ea_guid] nvarchar(50),
	[VisualType] varchar(100),
	CONSTRAINT [pk_stereotypes] PRIMARY KEY CLUSTERED ([AppliesTo] ASC,[Stereotype] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_stereotypes_stereotype] 
 ON [t_stereotypes] ([Stereotype] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_stereotypes_eaguid] 
 ON [t_stereotypes] ([ea_guid] ASC)
GO


CREATE TABLE [t_taggedvalue]
(
	[PropertyID] nvarchar(40) NOT NULL,
	[ElementID] nvarchar(40),
	[BaseClass] nvarchar(100) NOT NULL,
	[TagValue] nvarchar(max),
	[Notes] nvarchar(max),
	CONSTRAINT [pk_taggedvalue] PRIMARY KEY CLUSTERED ([PropertyID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_taggedvalue_elementid] 
 ON [t_taggedvalue] ([ElementID] ASC)
GO


CREATE TABLE [t_tasks]
(
	[TaskID] int NOT NULL IDENTITY (1, 1),
	[Name] nvarchar(255),
	[TaskType] nvarchar(255),
	[NOTES] nvarchar(max),
	[Priority] nvarchar(255),
	[Status] nvarchar(255),
	[Owner] nvarchar(255),
	[StartDate] datetime,
	[EndDate] datetime,
	[Phase] nvarchar(50),
	[History] nvarchar(max),
	[Percent] int,
	[TotalTime] int,
	[ActualTime] int,
	[AssignedTo] nvarchar(100),
	CONSTRAINT [pk_tasks] PRIMARY KEY CLUSTERED ([TaskID] ASC)
)
GO

CREATE TABLE [t_tcf]
(
	[TCFID] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[Weight] float DEFAULT ((1)),
	[Value] float DEFAULT ((0)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_tcf] PRIMARY KEY CLUSTERED ([TCFID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_tcf_weight] 
 ON [t_tcf] ([Weight] ASC)
GO


CREATE TABLE [t_template]
(
	[TemplateID] nvarchar(40) NOT NULL,
	[TemplateType] nvarchar(50) NOT NULL,
	[TemplateName] nvarchar(100) NOT NULL,
	[Notes] nvarchar(255),
	[Style] nvarchar(255),
	[Template] nvarchar(max),
	CONSTRAINT [pk_template] PRIMARY KEY CLUSTERED ([TemplateID] ASC)
)
GO

CREATE TABLE [t_testclass]
(
	[TestClass] nvarchar(50) NOT NULL,
	[Description] nvarchar(50),
	CONSTRAINT [pk_testclass] PRIMARY KEY CLUSTERED ([TestClass] ASC)
)
GO

CREATE TABLE [t_testplans]
(
	[PlanID] nvarchar(50) NOT NULL,
	[Category] nvarchar(100) NOT NULL,
	[Name] nvarchar(150) NOT NULL,
	[Author] nvarchar(255) NOT NULL,
	[Notes] nvarchar(max),
	[TestPlan] nvarchar(max) NOT NULL,
	CONSTRAINT [pk_testplans] PRIMARY KEY CLUSTERED ([PlanID] ASC)
)
GO

CREATE TABLE [t_testtypes]
(
	[TestType] nvarchar(12) NOT NULL,
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(255),
	CONSTRAINT [pk_testtypes] PRIMARY KEY CLUSTERED ([TestType] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_testtypes_numericweight] 
 ON [t_testtypes] ([NumericWeight] ASC)
GO


CREATE TABLE [t_trxtypes]
(
	[Description] nvarchar(50),
	[NumericWeight] float DEFAULT ((1)),
	[Notes] nvarchar(max),
	[TRX] nvarchar(255),
	[TRX_ID] int NOT NULL IDENTITY (1, 1),
	[Style] nvarchar(max),
	CONSTRAINT [pk_trxtypes] PRIMARY KEY CLUSTERED ([TRX_ID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_trxtypes_description] 
 ON [t_trxtypes] ([Description] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_trxtypes_numericweight] 
 ON [t_trxtypes] ([NumericWeight] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_trxtypes_trx] 
 ON [t_trxtypes] ([TRX] ASC)
GO


CREATE TABLE [t_umlpattern]
(
	[PatternID] int NOT NULL IDENTITY (1, 1),
	[PatternCategory] nvarchar(100),
	[PatternName] nvarchar(150),
	[Style] nvarchar(255),
	[Notes] nvarchar(max),
	[PatternXML] nvarchar(max),
	[Version] nvarchar(50),
	CONSTRAINT [pk_umlpattern] PRIMARY KEY CLUSTERED ([PatternID] ASC)
)
GO

CREATE TABLE [t_version]
(
	[ElementID] nvarchar(50) NOT NULL,
	[VersionID] nvarchar(255) NOT NULL,
	[ElementType] nvarchar(100),
	[Flags] nvarchar(255),
	[ExternalFile] nvarchar(255),
	[Notes] nvarchar(255),
	[Owner] nvarchar(255),
	[VersionDate] datetime,
	[Branch] nvarchar(255),
	[ElementXML] nvarchar(max),
	CONSTRAINT [pk_version] PRIMARY KEY CLUSTERED ([ElementID] ASC,[VersionID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_version_elementid] 
 ON [t_version] ([ElementID] ASC)
GO


CREATE TABLE [t_xref]
(
	[XrefID] nvarchar(255) NOT NULL,
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	[Visibility] nvarchar(255),
	[Namespace] nvarchar(255),
	[Requirement] nvarchar(255),
	[Constraint] nvarchar(255),
	[Behavior] nvarchar(255),
	[Partition] nvarchar(255),
	[Description] nvarchar(max),
	[Client] nvarchar(255),
	[Supplier] nvarchar(255),
	[Link] nvarchar(255),
	CONSTRAINT [pk_xref] PRIMARY KEY CLUSTERED ([XrefID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_xref_client] 
 ON [t_xref] ([Client] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xref_name] 
 ON [t_xref] ([Name] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xref_supplier] 
 ON [t_xref] ([Supplier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xref_type] 
 ON [t_xref] ([Type] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xref_nametype] 
 ON [t_xref] ([Name] ASC) 
 INCLUDE (Type)
GO


CREATE TABLE [t_xrefsystem]
(
	[XrefID] nvarchar(255) NOT NULL,
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	[Visibility] nvarchar(255),
	[Namespace] nvarchar(255),
	[Requirement] nvarchar(255),
	[Constraint] nvarchar(255),
	[Behavior] nvarchar(255),
	[Partition] nvarchar(255),
	[Description] nvarchar(max),
	[Client] nvarchar(255),
	[Supplier] nvarchar(255),
	[Link] nvarchar(255),
	[ToolID] nvarchar(50),
	CONSTRAINT [pk_xrefsystem] PRIMARY KEY CLUSTERED ([XrefID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_xrefsystem_client] 
 ON [t_xrefsystem] ([Client] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xrefsystem_supplier] 
 ON [t_xrefsystem] ([Supplier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xrefsystem_type] 
 ON [t_xrefsystem] ([Type] ASC)
GO


CREATE TABLE [t_xrefuser]
(
	[XrefID] nvarchar(255) NOT NULL,
	[Name] nvarchar(255),
	[Type] nvarchar(255),
	[Visibility] nvarchar(255),
	[Namespace] nvarchar(255),
	[Requirement] nvarchar(255),
	[Constraint] nvarchar(255),
	[Behavior] nvarchar(255),
	[Partition] nvarchar(255),
	[Description] nvarchar(max),
	[Client] nvarchar(255),
	[Supplier] nvarchar(255),
	[Link] nvarchar(255),
	[ToolID] nvarchar(50),
	CONSTRAINT [pk_xrefuser] PRIMARY KEY CLUSTERED ([XrefID] ASC)
)
GO
CREATE NONCLUSTERED INDEX [ix_xrefuser_client] 
 ON [t_xrefuser] ([Client] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xrefuser_supplier] 
 ON [t_xrefuser] ([Supplier] ASC)
GO
CREATE NONCLUSTERED INDEX [ix_xrefuser_type] 
 ON [t_xrefuser] ([Type] ASC)
GO


CREATE TABLE [dbo].[usys_schema]
(
	[V1558] varchar(255) NOT NULL,
	CONSTRAINT [PK_usys_schema] PRIMARY KEY CLUSTERED ([V1558] ASC)
)
GO

CREATE TABLE [usys_system]
(
	[Property] nvarchar(50) NOT NULL,
	[Value] nvarchar(50),
	CONSTRAINT [pk_usyssystem] PRIMARY KEY CLUSTERED ([Property] ASC)
)
GO

CREATE TABLE [usysOldTables]
(
	[TableName] nvarchar(50),
	[NewName] nvarchar(50),
	[RelOrder] int DEFAULT ((0)),
	[FixCode] int NOT NULL DEFAULT ((0))
)
GO
CREATE CLUSTERED INDEX [ix_usysoldtables_tablename] 
 ON [usysOldTables] ([TableName] ASC)
GO


CREATE TABLE [usysQueries]
(
	[QueryName] nvarchar(50),
	[NewName] nvarchar(50),
	[FixCode] int NOT NULL DEFAULT ((0))
)
GO
CREATE CLUSTERED INDEX [ix_usysqueries_queryname] 
 ON [usysQueries] ([QueryName] ASC)
GO


CREATE TABLE [usysTables]
(
	[TableName] nvarchar(50) NOT NULL,
	[RelOrder] int DEFAULT ((0)),
	[DisplayName] nvarchar(50),
	[FromVer] nvarchar(50),
	[ToVer] nvarchar(50),
	CONSTRAINT [pk_usystables] PRIMARY KEY CLUSTERED ([TableName] ASC)
)
GO


